name: smarsh
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: null
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  email_validator: null
  equatable: ^2.0.5
  file_picker: ^5.5.0
  firebase_analytics: null
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0

  #!SECTION
  #
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.5
  hive: null
  hive_flutter: null
  intl: null
  path_provider: ^2.1.1
  provider: null
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  to_csv: ^2.1.0

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/android_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/android_icon.png"
    background_color: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
